default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  timeout: 5000

development:
  <<: *default
  database: groove_core_development
  username: groovecore_admin
  password: gc_js_t
  host: localhost
  port: 5432

test:
  <<: *default
  database: groove_core_test
  username: groovecore_admin
  password: gc_js_t
  host: localhost
  port: 5432

production:
  <<: *default
  database: dbvo22nhno3gse
  username: obbskwdrpvbsgm
  password: 905b844f6f1121e05077f08799f327dff2a64e9c7157e8f5aa98c3b1aaa7433a
  host: ec2-44-206-204-65.compute-1.amazonaws.com
  port: 5432
